### ISSUE TITLE
Data for ReRaM cell

### ISSUE THREAD

**Issue by ratul619** [google/skywater-pdk-libs-sky130_fd_pr_reram#21]
Hi any published data regarding below for rram cell

Forming voltage 
Set,reset voltage 
HRS,LRS resistances
Compliance current 

Thanks

**Comment by mguthaus** [comment]
There is at least one publication with skywater data. This seems to form the suggested models.

"(PDF) High-Density Multiple Bits-per-Cell 1T4R RRAM Array with Gradual SET/RESET and its Effectiveness for Deep Learning" https://www.researchgate.net/publication/339262085_High-Density_Multiple_Bits-per-Cell_1T4R_RRAM_Array_with_Gradual_SETRESET_and_its_Effectiveness_for_Deep_Learning

**Comment by mithro** [comment]
Seems like this should be added to the references?

**Comment by ratul619** [comment]
Thanks but seems the data is not "directly" mentioned in the paper - about voltages and current requirements. 
But rather describes a novel technique they adopted (set/reset pulse programming in adaptive way). Any idea about more such references OR some graphs ?

**Comment by QuantamHD** [comment]
@ratul619 Please see https://github.com/google/skywater-pdk-libs-sky130_fd_pr_reram/pull/24 for most of the information. It's still in progress, but should cover the basic reram cases.

**Comment by QuantamHD** [comment]
Added the base information in #24
